// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: indrive.proto

package indrivepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pickup        *Point                 `protobuf:"bytes,1,opt,name=pickup,proto3" json:"pickup,omitempty"`
	Dropoff       *Point                 `protobuf:"bytes,2,opt,name=dropoff,proto3" json:"dropoff,omitempty"`
	VehicleType   string                 `protobuf:"bytes,3,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`        // sedan | suv | luxury | motorcycle
	SurgeEligible bool                   `protobuf:"varint,4,opt,name=surge_eligible,json=surgeEligible,proto3" json:"surge_eligible,omitempty"` // apply dynamic surge multiplier
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`                                 // ISO 4217, e.g. "USD"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FareRequest) Reset() {
	*x = FareRequest{}
	mi := &file_indrive_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FareRequest) ProtoMessage() {}

func (x *FareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indrive_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FareRequest.ProtoReflect.Descriptor instead.
func (*FareRequest) Descriptor() ([]byte, []int) {
	return file_indrive_proto_rawDescGZIP(), []int{0}
}

func (x *FareRequest) GetPickup() *Point {
	if x != nil {
		return x.Pickup
	}
	return nil
}

func (x *FareRequest) GetDropoff() *Point {
	if x != nil {
		return x.Dropoff
	}
	return nil
}

func (x *FareRequest) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *FareRequest) GetSurgeEligible() bool {
	if x != nil {
		return x.SurgeEligible
	}
	return false
}

func (x *FareRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type FinalizeRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Pickup                *Point                 `protobuf:"bytes,1,opt,name=pickup,proto3" json:"pickup,omitempty"`
	Dropoff               *Point                 `protobuf:"bytes,2,opt,name=dropoff,proto3" json:"dropoff,omitempty"`
	ActualDistanceMeters  float64                `protobuf:"fixed64,3,opt,name=actual_distance_meters,json=actualDistanceMeters,proto3" json:"actual_distance_meters,omitempty"`
	ActualDurationSeconds uint32                 `protobuf:"varint,4,opt,name=actual_duration_seconds,json=actualDurationSeconds,proto3" json:"actual_duration_seconds,omitempty"`
	VehicleType           string                 `protobuf:"bytes,5,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	Currency              string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *FinalizeRequest) Reset() {
	*x = FinalizeRequest{}
	mi := &file_indrive_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeRequest) ProtoMessage() {}

func (x *FinalizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indrive_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeRequest.ProtoReflect.Descriptor instead.
func (*FinalizeRequest) Descriptor() ([]byte, []int) {
	return file_indrive_proto_rawDescGZIP(), []int{1}
}

func (x *FinalizeRequest) GetPickup() *Point {
	if x != nil {
		return x.Pickup
	}
	return nil
}

func (x *FinalizeRequest) GetDropoff() *Point {
	if x != nil {
		return x.Dropoff
	}
	return nil
}

func (x *FinalizeRequest) GetActualDistanceMeters() float64 {
	if x != nil {
		return x.ActualDistanceMeters
	}
	return 0
}

func (x *FinalizeRequest) GetActualDurationSeconds() uint32 {
	if x != nil {
		return x.ActualDurationSeconds
	}
	return 0
}

func (x *FinalizeRequest) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *FinalizeRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_indrive_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_indrive_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_indrive_proto_rawDescGZIP(), []int{2}
}

func (x *Point) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Point) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Point) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type FareEstimate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BaseFare        float64                `protobuf:"fixed64,1,opt,name=base_fare,json=baseFare,proto3" json:"base_fare,omitempty"`
	DistanceFare    float64                `protobuf:"fixed64,2,opt,name=distance_fare,json=distanceFare,proto3" json:"distance_fare,omitempty"`
	TimeFare        float64                `protobuf:"fixed64,3,opt,name=time_fare,json=timeFare,proto3" json:"time_fare,omitempty"`
	SurgeMultiplier float64                `protobuf:"fixed64,4,opt,name=surge_multiplier,json=surgeMultiplier,proto3" json:"surge_multiplier,omitempty"`
	BookingFee      float64                `protobuf:"fixed64,5,opt,name=booking_fee,json=bookingFee,proto3" json:"booking_fee,omitempty"`
	SuggestedFare   float64                `protobuf:"fixed64,6,opt,name=suggested_fare,json=suggestedFare,proto3" json:"suggested_fare,omitempty"` // total the rider should offer
	MinimumFare     float64                `protobuf:"fixed64,7,opt,name=minimum_fare,json=minimumFare,proto3" json:"minimum_fare,omitempty"`
	Currency        string                 `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`
	// route metadata returned for the UI
	DistanceMeters  float64 `protobuf:"fixed64,9,opt,name=distance_meters,json=distanceMeters,proto3" json:"distance_meters,omitempty"`
	DurationSeconds uint32  `protobuf:"varint,10,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	// optional OSRM-style polyline once routing data is wired
	EncodedPolyline string `protobuf:"bytes,11,opt,name=encoded_polyline,json=encodedPolyline,proto3" json:"encoded_polyline,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FareEstimate) Reset() {
	*x = FareEstimate{}
	mi := &file_indrive_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FareEstimate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FareEstimate) ProtoMessage() {}

func (x *FareEstimate) ProtoReflect() protoreflect.Message {
	mi := &file_indrive_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FareEstimate.ProtoReflect.Descriptor instead.
func (*FareEstimate) Descriptor() ([]byte, []int) {
	return file_indrive_proto_rawDescGZIP(), []int{3}
}

func (x *FareEstimate) GetBaseFare() float64 {
	if x != nil {
		return x.BaseFare
	}
	return 0
}

func (x *FareEstimate) GetDistanceFare() float64 {
	if x != nil {
		return x.DistanceFare
	}
	return 0
}

func (x *FareEstimate) GetTimeFare() float64 {
	if x != nil {
		return x.TimeFare
	}
	return 0
}

func (x *FareEstimate) GetSurgeMultiplier() float64 {
	if x != nil {
		return x.SurgeMultiplier
	}
	return 0
}

func (x *FareEstimate) GetBookingFee() float64 {
	if x != nil {
		return x.BookingFee
	}
	return 0
}

func (x *FareEstimate) GetSuggestedFare() float64 {
	if x != nil {
		return x.SuggestedFare
	}
	return 0
}

func (x *FareEstimate) GetMinimumFare() float64 {
	if x != nil {
		return x.MinimumFare
	}
	return 0
}

func (x *FareEstimate) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *FareEstimate) GetDistanceMeters() float64 {
	if x != nil {
		return x.DistanceMeters
	}
	return 0
}

func (x *FareEstimate) GetDurationSeconds() uint32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *FareEstimate) GetEncodedPolyline() string {
	if x != nil {
		return x.EncodedPolyline
	}
	return ""
}

type CreateRideRequestMsg struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RiderId            string                 `protobuf:"bytes,1,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	RideId             string                 `protobuf:"bytes,2,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"` // generated by API Gateway
	Pickup             *Point                 `protobuf:"bytes,3,opt,name=pickup,proto3" json:"pickup,omitempty"`
	Dropoff            *Point                 `protobuf:"bytes,4,opt,name=dropoff,proto3" json:"dropoff,omitempty"`
	RiderProposedFare  float64                `protobuf:"fixed64,5,opt,name=rider_proposed_fare,json=riderProposedFare,proto3" json:"rider_proposed_fare,omitempty"` // InDrive: rider posts their own price
	Currency           string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	VehicleType        string                 `protobuf:"bytes,7,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	SearchRadiusMeters uint32                 `protobuf:"varint,8,opt,name=search_radius_meters,json=searchRadiusMeters,proto3" json:"search_radius_meters,omitempty"` // default 5000m
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateRideRequestMsg) Reset() {
	*x = CreateRideRequestMsg{}
	mi := &file_indrive_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRideRequestMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRideRequestMsg) ProtoMessage() {}

func (x *CreateRideRequestMsg) ProtoReflect() protoreflect.Message {
	mi := &file_indrive_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRideRequestMsg.ProtoReflect.Descriptor instead.
func (*CreateRideRequestMsg) Descriptor() ([]byte, []int) {
	return file_indrive_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRideRequestMsg) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *CreateRideRequestMsg) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *CreateRideRequestMsg) GetPickup() *Point {
	if x != nil {
		return x.Pickup
	}
	return nil
}

func (x *CreateRideRequestMsg) GetDropoff() *Point {
	if x != nil {
		return x.Dropoff
	}
	return nil
}

func (x *CreateRideRequestMsg) GetRiderProposedFare() float64 {
	if x != nil {
		return x.RiderProposedFare
	}
	return 0
}

func (x *CreateRideRequestMsg) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateRideRequestMsg) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *CreateRideRequestMsg) GetSearchRadiusMeters() uint32 {
	if x != nil {
		return x.SearchRadiusMeters
	}
	return 0
}

type RideRequestAck struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RideId            string                 `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	NotifiedDriverIds []string               `protobuf:"bytes,2,rep,name=notified_driver_ids,json=notifiedDriverIds,proto3" json:"notified_driver_ids,omitempty"`
	NearbyDriverCount uint32                 `protobuf:"varint,3,opt,name=nearby_driver_count,json=nearbyDriverCount,proto3" json:"nearby_driver_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RideRequestAck) Reset() {
	*x = RideRequestAck{}
	mi := &file_indrive_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RideRequestAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RideRequestAck) ProtoMessage() {}

func (x *RideRequestAck) ProtoReflect() protoreflect.Message {
	mi := &file_indrive_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RideRequestAck.ProtoReflect.Descriptor instead.
func (*RideRequestAck) Descriptor() ([]byte, []int) {
	return file_indrive_proto_rawDescGZIP(), []int{5}
}

func (x *RideRequestAck) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *RideRequestAck) GetNotifiedDriverIds() []string {
	if x != nil {
		return x.NotifiedDriverIds
	}
	return nil
}

func (x *RideRequestAck) GetNearbyDriverCount() uint32 {
	if x != nil {
		return x.NearbyDriverCount
	}
	return 0
}

type DriverBid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RideId        string                 `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	CounterOffer  float64                `protobuf:"fixed64,3,opt,name=counter_offer,json=counterOffer,proto3" json:"counter_offer,omitempty"` // driver's counter price vs rider's ask
	EtaSeconds    uint32                 `protobuf:"varint,4,opt,name=eta_seconds,json=etaSeconds,proto3" json:"eta_seconds,omitempty"`        // pickup ETA
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverBid) Reset() {
	*x = DriverBid{}
	mi := &file_indrive_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverBid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverBid) ProtoMessage() {}

func (x *DriverBid) ProtoReflect() protoreflect.Message {
	mi := &file_indrive_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverBid.ProtoReflect.Descriptor instead.
func (*DriverBid) Descriptor() ([]byte, []int) {
	return file_indrive_proto_rawDescGZIP(), []int{6}
}

func (x *DriverBid) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *DriverBid) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *DriverBid) GetCounterOffer() float64 {
	if x != nil {
		return x.CounterOffer
	}
	return 0
}

func (x *DriverBid) GetEtaSeconds() uint32 {
	if x != nil {
		return x.EtaSeconds
	}
	return 0
}

func (x *DriverBid) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type BidAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BidId         string                 `protobuf:"bytes,1,opt,name=bid_id,json=bidId,proto3" json:"bid_id,omitempty"`
	TtlSeconds    uint32                 `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"` // bid validity (120s default)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidAck) Reset() {
	*x = BidAck{}
	mi := &file_indrive_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidAck) ProtoMessage() {}

func (x *BidAck) ProtoReflect() protoreflect.Message {
	mi := &file_indrive_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidAck.ProtoReflect.Descriptor instead.
func (*BidAck) Descriptor() ([]byte, []int) {
	return file_indrive_proto_rawDescGZIP(), []int{7}
}

func (x *BidAck) GetBidId() string {
	if x != nil {
		return x.BidId
	}
	return ""
}

func (x *BidAck) GetTtlSeconds() uint32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type AcceptBidMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RideId        string                 `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	BidId         string                 `protobuf:"bytes,2,opt,name=bid_id,json=bidId,proto3" json:"bid_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,3,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptBidMsg) Reset() {
	*x = AcceptBidMsg{}
	mi := &file_indrive_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptBidMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptBidMsg) ProtoMessage() {}

func (x *AcceptBidMsg) ProtoReflect() protoreflect.Message {
	mi := &file_indrive_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptBidMsg.ProtoReflect.Descriptor instead.
func (*AcceptBidMsg) Descriptor() ([]byte, []int) {
	return file_indrive_proto_rawDescGZIP(), []int{8}
}

func (x *AcceptBidMsg) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *AcceptBidMsg) GetBidId() string {
	if x != nil {
		return x.BidId
	}
	return ""
}

func (x *AcceptBidMsg) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

type AcceptAck struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AssignedDriverId string                 `protobuf:"bytes,2,opt,name=assigned_driver_id,json=assignedDriverId,proto3" json:"assigned_driver_id,omitempty"`
	AgreedFare       float64                `protobuf:"fixed64,3,opt,name=agreed_fare,json=agreedFare,proto3" json:"agreed_fare,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AcceptAck) Reset() {
	*x = AcceptAck{}
	mi := &file_indrive_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptAck) ProtoMessage() {}

func (x *AcceptAck) ProtoReflect() protoreflect.Message {
	mi := &file_indrive_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptAck.ProtoReflect.Descriptor instead.
func (*AcceptAck) Descriptor() ([]byte, []int) {
	return file_indrive_proto_rawDescGZIP(), []int{9}
}

func (x *AcceptAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AcceptAck) GetAssignedDriverId() string {
	if x != nil {
		return x.AssignedDriverId
	}
	return ""
}

func (x *AcceptAck) GetAgreedFare() float64 {
	if x != nil {
		return x.AgreedFare
	}
	return 0
}

type CancelRideMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RideId        string                 `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	RiderId       string                 `protobuf:"bytes,2,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRideMsg) Reset() {
	*x = CancelRideMsg{}
	mi := &file_indrive_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRideMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRideMsg) ProtoMessage() {}

func (x *CancelRideMsg) ProtoReflect() protoreflect.Message {
	mi := &file_indrive_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRideMsg.ProtoReflect.Descriptor instead.
func (*CancelRideMsg) Descriptor() ([]byte, []int) {
	return file_indrive_proto_rawDescGZIP(), []int{10}
}

func (x *CancelRideMsg) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *CancelRideMsg) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_indrive_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_indrive_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_indrive_proto_rawDescGZIP(), []int{11}
}

var File_indrive_proto protoreflect.FileDescriptor

const file_indrive_proto_rawDesc = "" +
	"\n" +
	"\rindrive.proto\x12\aindrive\"\xc5\x01\n" +
	"\vFareRequest\x12&\n" +
	"\x06pickup\x18\x01 \x01(\v2\x0e.indrive.PointR\x06pickup\x12(\n" +
	"\adropoff\x18\x02 \x01(\v2\x0e.indrive.PointR\adropoff\x12!\n" +
	"\fvehicle_type\x18\x03 \x01(\tR\vvehicleType\x12%\n" +
	"\x0esurge_eligible\x18\x04 \x01(\bR\rsurgeEligible\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\"\x90\x02\n" +
	"\x0fFinalizeRequest\x12&\n" +
	"\x06pickup\x18\x01 \x01(\v2\x0e.indrive.PointR\x06pickup\x12(\n" +
	"\adropoff\x18\x02 \x01(\v2\x0e.indrive.PointR\adropoff\x124\n" +
	"\x16actual_distance_meters\x18\x03 \x01(\x01R\x14actualDistanceMeters\x126\n" +
	"\x17actual_duration_seconds\x18\x04 \x01(\rR\x15actualDurationSeconds\x12!\n" +
	"\fvehicle_type\x18\x05 \x01(\tR\vvehicleType\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\"[\n" +
	"\x05Point\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"\x9e\x03\n" +
	"\fFareEstimate\x12\x1b\n" +
	"\tbase_fare\x18\x01 \x01(\x01R\bbaseFare\x12#\n" +
	"\rdistance_fare\x18\x02 \x01(\x01R\fdistanceFare\x12\x1b\n" +
	"\ttime_fare\x18\x03 \x01(\x01R\btimeFare\x12)\n" +
	"\x10surge_multiplier\x18\x04 \x01(\x01R\x0fsurgeMultiplier\x12\x1f\n" +
	"\vbooking_fee\x18\x05 \x01(\x01R\n" +
	"bookingFee\x12%\n" +
	"\x0esuggested_fare\x18\x06 \x01(\x01R\rsuggestedFare\x12!\n" +
	"\fminimum_fare\x18\a \x01(\x01R\vminimumFare\x12\x1a\n" +
	"\bcurrency\x18\b \x01(\tR\bcurrency\x12'\n" +
	"\x0fdistance_meters\x18\t \x01(\x01R\x0edistanceMeters\x12)\n" +
	"\x10duration_seconds\x18\n" +
	" \x01(\rR\x0fdurationSeconds\x12)\n" +
	"\x10encoded_polyline\x18\v \x01(\tR\x0fencodedPolyline\"\xbd\x02\n" +
	"\x14CreateRideRequestMsg\x12\x19\n" +
	"\brider_id\x18\x01 \x01(\tR\ariderId\x12\x17\n" +
	"\aride_id\x18\x02 \x01(\tR\x06rideId\x12&\n" +
	"\x06pickup\x18\x03 \x01(\v2\x0e.indrive.PointR\x06pickup\x12(\n" +
	"\adropoff\x18\x04 \x01(\v2\x0e.indrive.PointR\adropoff\x12.\n" +
	"\x13rider_proposed_fare\x18\x05 \x01(\x01R\x11riderProposedFare\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12!\n" +
	"\fvehicle_type\x18\a \x01(\tR\vvehicleType\x120\n" +
	"\x14search_radius_meters\x18\b \x01(\rR\x12searchRadiusMeters\"\x89\x01\n" +
	"\x0eRideRequestAck\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\tR\x06rideId\x12.\n" +
	"\x13notified_driver_ids\x18\x02 \x03(\tR\x11notifiedDriverIds\x12.\n" +
	"\x13nearby_driver_count\x18\x03 \x01(\rR\x11nearbyDriverCount\"\xa3\x01\n" +
	"\tDriverBid\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\tR\x06rideId\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\x12#\n" +
	"\rcounter_offer\x18\x03 \x01(\x01R\fcounterOffer\x12\x1f\n" +
	"\veta_seconds\x18\x04 \x01(\rR\n" +
	"etaSeconds\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\"@\n" +
	"\x06BidAck\x12\x15\n" +
	"\x06bid_id\x18\x01 \x01(\tR\x05bidId\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\rR\n" +
	"ttlSeconds\"[\n" +
	"\fAcceptBidMsg\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\tR\x06rideId\x12\x15\n" +
	"\x06bid_id\x18\x02 \x01(\tR\x05bidId\x12\x1b\n" +
	"\tdriver_id\x18\x03 \x01(\tR\bdriverId\"t\n" +
	"\tAcceptAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12,\n" +
	"\x12assigned_driver_id\x18\x02 \x01(\tR\x10assignedDriverId\x12\x1f\n" +
	"\vagreed_fare\x18\x03 \x01(\x01R\n" +
	"agreedFare\"C\n" +
	"\rCancelRideMsg\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\tR\x06rideId\x12\x19\n" +
	"\brider_id\x18\x02 \x01(\tR\ariderId\"\a\n" +
	"\x05Empty2\x8e\x01\n" +
	"\rPricingEngine\x12<\n" +
	"\rCalculateFare\x12\x14.indrive.FareRequest\x1a\x15.indrive.FareEstimate\x12?\n" +
	"\fFinalizeFare\x12\x18.indrive.FinalizeRequest\x1a\x15.indrive.FareEstimate2\x88\x02\n" +
	"\fRideMatching\x12K\n" +
	"\x11CreateRideRequest\x12\x1d.indrive.CreateRideRequestMsg\x1a\x17.indrive.RideRequestAck\x126\n" +
	"\x0fSubmitDriverBid\x12\x12.indrive.DriverBid\x1a\x0f.indrive.BidAck\x126\n" +
	"\tAcceptBid\x12\x15.indrive.AcceptBidMsg\x1a\x12.indrive.AcceptAck\x12;\n" +
	"\x11CancelRideRequest\x12\x16.indrive.CancelRideMsg\x1a\x0e.indrive.EmptyB\x1eZ\x1cindriveclone/proto/indrivepbb\x06proto3"

var (
	file_indrive_proto_rawDescOnce sync.Once
	file_indrive_proto_rawDescData []byte
)

func file_indrive_proto_rawDescGZIP() []byte {
	file_indrive_proto_rawDescOnce.Do(func() {
		file_indrive_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_indrive_proto_rawDesc), len(file_indrive_proto_rawDesc)))
	})
	return file_indrive_proto_rawDescData
}

var file_indrive_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_indrive_proto_goTypes = []any{
	(*FareRequest)(nil),          // 0: indrive.FareRequest
	(*FinalizeRequest)(nil),      // 1: indrive.FinalizeRequest
	(*Point)(nil),                // 2: indrive.Point
	(*FareEstimate)(nil),         // 3: indrive.FareEstimate
	(*CreateRideRequestMsg)(nil), // 4: indrive.CreateRideRequestMsg
	(*RideRequestAck)(nil),       // 5: indrive.RideRequestAck
	(*DriverBid)(nil),            // 6: indrive.DriverBid
	(*BidAck)(nil),               // 7: indrive.BidAck
	(*AcceptBidMsg)(nil),         // 8: indrive.AcceptBidMsg
	(*AcceptAck)(nil),            // 9: indrive.AcceptAck
	(*CancelRideMsg)(nil),        // 10: indrive.CancelRideMsg
	(*Empty)(nil),                // 11: indrive.Empty
}
var file_indrive_proto_depIdxs = []int32{
	2,  // 0: indrive.FareRequest.pickup:type_name -> indrive.Point
	2,  // 1: indrive.FareRequest.dropoff:type_name -> indrive.Point
	2,  // 2: indrive.FinalizeRequest.pickup:type_name -> indrive.Point
	2,  // 3: indrive.FinalizeRequest.dropoff:type_name -> indrive.Point
	2,  // 4: indrive.CreateRideRequestMsg.pickup:type_name -> indrive.Point
	2,  // 5: indrive.CreateRideRequestMsg.dropoff:type_name -> indrive.Point
	0,  // 6: indrive.PricingEngine.CalculateFare:input_type -> indrive.FareRequest
	1,  // 7: indrive.PricingEngine.FinalizeFare:input_type -> indrive.FinalizeRequest
	4,  // 8: indrive.RideMatching.CreateRideRequest:input_type -> indrive.CreateRideRequestMsg
	6,  // 9: indrive.RideMatching.SubmitDriverBid:input_type -> indrive.DriverBid
	8,  // 10: indrive.RideMatching.AcceptBid:input_type -> indrive.AcceptBidMsg
	10, // 11: indrive.RideMatching.CancelRideRequest:input_type -> indrive.CancelRideMsg
	3,  // 12: indrive.PricingEngine.CalculateFare:output_type -> indrive.FareEstimate
	3,  // 13: indrive.PricingEngine.FinalizeFare:output_type -> indrive.FareEstimate
	5,  // 14: indrive.RideMatching.CreateRideRequest:output_type -> indrive.RideRequestAck
	7,  // 15: indrive.RideMatching.SubmitDriverBid:output_type -> indrive.BidAck
	9,  // 16: indrive.RideMatching.AcceptBid:output_type -> indrive.AcceptAck
	11, // 17: indrive.RideMatching.CancelRideRequest:output_type -> indrive.Empty
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_indrive_proto_init() }
func file_indrive_proto_init() {
	if File_indrive_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_indrive_proto_rawDesc), len(file_indrive_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_indrive_proto_goTypes,
		DependencyIndexes: file_indrive_proto_depIdxs,
		MessageInfos:      file_indrive_proto_msgTypes,
	}.Build()
	File_indrive_proto = out.File
	file_indrive_proto_goTypes = nil
	file_indrive_proto_depIdxs = nil
}
