// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: indrive.proto

package indrivepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PricingEngine_CalculateFare_FullMethodName = "/indrive.PricingEngine/CalculateFare"
	PricingEngine_FinalizeFare_FullMethodName  = "/indrive.PricingEngine/FinalizeFare"
)

// PricingEngineClient is the client API for PricingEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PricingEngineClient interface {
	// Suggested fare + route metadata for a rider's A -> B request.
	CalculateFare(ctx context.Context, in *FareRequest, opts ...grpc.CallOption) (*FareEstimate, error)
	// Final fare after the ride completes (actual distance + time + surge).
	FinalizeFare(ctx context.Context, in *FinalizeRequest, opts ...grpc.CallOption) (*FareEstimate, error)
}

type pricingEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewPricingEngineClient(cc grpc.ClientConnInterface) PricingEngineClient {
	return &pricingEngineClient{cc}
}

func (c *pricingEngineClient) CalculateFare(ctx context.Context, in *FareRequest, opts ...grpc.CallOption) (*FareEstimate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FareEstimate)
	err := c.cc.Invoke(ctx, PricingEngine_CalculateFare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pricingEngineClient) FinalizeFare(ctx context.Context, in *FinalizeRequest, opts ...grpc.CallOption) (*FareEstimate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FareEstimate)
	err := c.cc.Invoke(ctx, PricingEngine_FinalizeFare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PricingEngineServer is the server API for PricingEngine service.
// All implementations must embed UnimplementedPricingEngineServer
// for forward compatibility.
type PricingEngineServer interface {
	// Suggested fare + route metadata for a rider's A -> B request.
	CalculateFare(context.Context, *FareRequest) (*FareEstimate, error)
	// Final fare after the ride completes (actual distance + time + surge).
	FinalizeFare(context.Context, *FinalizeRequest) (*FareEstimate, error)
	mustEmbedUnimplementedPricingEngineServer()
}

// UnimplementedPricingEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPricingEngineServer struct{}

func (UnimplementedPricingEngineServer) CalculateFare(context.Context, *FareRequest) (*FareEstimate, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateFare not implemented")
}
func (UnimplementedPricingEngineServer) FinalizeFare(context.Context, *FinalizeRequest) (*FareEstimate, error) {
	return nil, status.Error(codes.Unimplemented, "method FinalizeFare not implemented")
}
func (UnimplementedPricingEngineServer) mustEmbedUnimplementedPricingEngineServer() {}
func (UnimplementedPricingEngineServer) testEmbeddedByValue()                       {}

// UnsafePricingEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PricingEngineServer will
// result in compilation errors.
type UnsafePricingEngineServer interface {
	mustEmbedUnimplementedPricingEngineServer()
}

func RegisterPricingEngineServer(s grpc.ServiceRegistrar, srv PricingEngineServer) {
	// If the following call panics, it indicates UnimplementedPricingEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PricingEngine_ServiceDesc, srv)
}

func _PricingEngine_CalculateFare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PricingEngineServer).CalculateFare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PricingEngine_CalculateFare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PricingEngineServer).CalculateFare(ctx, req.(*FareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PricingEngine_FinalizeFare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PricingEngineServer).FinalizeFare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PricingEngine_FinalizeFare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PricingEngineServer).FinalizeFare(ctx, req.(*FinalizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PricingEngine_ServiceDesc is the grpc.ServiceDesc for PricingEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PricingEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "indrive.PricingEngine",
	HandlerType: (*PricingEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateFare",
			Handler:    _PricingEngine_CalculateFare_Handler,
		},
		{
			MethodName: "FinalizeFare",
			Handler:    _PricingEngine_FinalizeFare_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "indrive.proto",
}

const (
	RideMatching_CreateRideRequest_FullMethodName = "/indrive.RideMatching/CreateRideRequest"
	RideMatching_SubmitDriverBid_FullMethodName   = "/indrive.RideMatching/SubmitDriverBid"
	RideMatching_AcceptBid_FullMethodName         = "/indrive.RideMatching/AcceptBid"
	RideMatching_CancelRideRequest_FullMethodName = "/indrive.RideMatching/CancelRideRequest"
)

// RideMatchingClient is the client API for RideMatching service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RideMatchingClient interface {
	// Rider (via API Gateway) asks to find drivers near a pickup point.
	// Returns the ride_id and the list of driver ids that got notified.
	CreateRideRequest(ctx context.Context, in *CreateRideRequestMsg, opts ...grpc.CallOption) (*RideRequestAck, error)
	// A driver counter-offers a price for an open ride.
	SubmitDriverBid(ctx context.Context, in *DriverBid, opts ...grpc.CallOption) (*BidAck, error)
	// Rider accepts one of the counter-offers, locking in the driver.
	AcceptBid(ctx context.Context, in *AcceptBidMsg, opts ...grpc.CallOption) (*AcceptAck, error)
	// Rider cancels an open request (no driver assigned yet).
	CancelRideRequest(ctx context.Context, in *CancelRideMsg, opts ...grpc.CallOption) (*Empty, error)
}

type rideMatchingClient struct {
	cc grpc.ClientConnInterface
}

func NewRideMatchingClient(cc grpc.ClientConnInterface) RideMatchingClient {
	return &rideMatchingClient{cc}
}

func (c *rideMatchingClient) CreateRideRequest(ctx context.Context, in *CreateRideRequestMsg, opts ...grpc.CallOption) (*RideRequestAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RideRequestAck)
	err := c.cc.Invoke(ctx, RideMatching_CreateRideRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rideMatchingClient) SubmitDriverBid(ctx context.Context, in *DriverBid, opts ...grpc.CallOption) (*BidAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BidAck)
	err := c.cc.Invoke(ctx, RideMatching_SubmitDriverBid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rideMatchingClient) AcceptBid(ctx context.Context, in *AcceptBidMsg, opts ...grpc.CallOption) (*AcceptAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptAck)
	err := c.cc.Invoke(ctx, RideMatching_AcceptBid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rideMatchingClient) CancelRideRequest(ctx context.Context, in *CancelRideMsg, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, RideMatching_CancelRideRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RideMatchingServer is the server API for RideMatching service.
// All implementations must embed UnimplementedRideMatchingServer
// for forward compatibility.
type RideMatchingServer interface {
	// Rider (via API Gateway) asks to find drivers near a pickup point.
	// Returns the ride_id and the list of driver ids that got notified.
	CreateRideRequest(context.Context, *CreateRideRequestMsg) (*RideRequestAck, error)
	// A driver counter-offers a price for an open ride.
	SubmitDriverBid(context.Context, *DriverBid) (*BidAck, error)
	// Rider accepts one of the counter-offers, locking in the driver.
	AcceptBid(context.Context, *AcceptBidMsg) (*AcceptAck, error)
	// Rider cancels an open request (no driver assigned yet).
	CancelRideRequest(context.Context, *CancelRideMsg) (*Empty, error)
	mustEmbedUnimplementedRideMatchingServer()
}

// UnimplementedRideMatchingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRideMatchingServer struct{}

func (UnimplementedRideMatchingServer) CreateRideRequest(context.Context, *CreateRideRequestMsg) (*RideRequestAck, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRideRequest not implemented")
}
func (UnimplementedRideMatchingServer) SubmitDriverBid(context.Context, *DriverBid) (*BidAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitDriverBid not implemented")
}
func (UnimplementedRideMatchingServer) AcceptBid(context.Context, *AcceptBidMsg) (*AcceptAck, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptBid not implemented")
}
func (UnimplementedRideMatchingServer) CancelRideRequest(context.Context, *CancelRideMsg) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelRideRequest not implemented")
}
func (UnimplementedRideMatchingServer) mustEmbedUnimplementedRideMatchingServer() {}
func (UnimplementedRideMatchingServer) testEmbeddedByValue()                      {}

// UnsafeRideMatchingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RideMatchingServer will
// result in compilation errors.
type UnsafeRideMatchingServer interface {
	mustEmbedUnimplementedRideMatchingServer()
}

func RegisterRideMatchingServer(s grpc.ServiceRegistrar, srv RideMatchingServer) {
	// If the following call panics, it indicates UnimplementedRideMatchingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RideMatching_ServiceDesc, srv)
}

func _RideMatching_CreateRideRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRideRequestMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RideMatchingServer).CreateRideRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RideMatching_CreateRideRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RideMatchingServer).CreateRideRequest(ctx, req.(*CreateRideRequestMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _RideMatching_SubmitDriverBid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DriverBid)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RideMatchingServer).SubmitDriverBid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RideMatching_SubmitDriverBid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RideMatchingServer).SubmitDriverBid(ctx, req.(*DriverBid))
	}
	return interceptor(ctx, in, info, handler)
}

func _RideMatching_AcceptBid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptBidMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RideMatchingServer).AcceptBid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RideMatching_AcceptBid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RideMatchingServer).AcceptBid(ctx, req.(*AcceptBidMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _RideMatching_CancelRideRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRideMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RideMatchingServer).CancelRideRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RideMatching_CancelRideRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RideMatchingServer).CancelRideRequest(ctx, req.(*CancelRideMsg))
	}
	return interceptor(ctx, in, info, handler)
}

// RideMatching_ServiceDesc is the grpc.ServiceDesc for RideMatching service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RideMatching_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "indrive.RideMatching",
	HandlerType: (*RideMatchingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRideRequest",
			Handler:    _RideMatching_CreateRideRequest_Handler,
		},
		{
			MethodName: "SubmitDriverBid",
			Handler:    _RideMatching_SubmitDriverBid_Handler,
		},
		{
			MethodName: "AcceptBid",
			Handler:    _RideMatching_AcceptBid_Handler,
		},
		{
			MethodName: "CancelRideRequest",
			Handler:    _RideMatching_CancelRideRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "indrive.proto",
}
